apiVersion: v1
kind: ConfigMap
metadata:
  name: isilon-exporter-config
  namespace: monitoring
data:
  clusters.yaml: |
    clusters:
      - host: 10.142.94.20
        port: "8080"
        username: admin
        password_env: ISILON_CLUSTER_PASSWORD
        site: ""
      - host: 10.142.94.17
        port: "8080"
        username: admin
        password_env: ISILON_CLUSTER2_PASSWORD
        site: ""
